import type { Category, Brand, Attribute } from './types';

export const BRANDS: Brand[] = [
    { name: 'Audemars Piguet', id: 694 },
    { name: 'Bulgari', id: 1239 },
    { name: 'Burberry', id: 2265 },
    { name: 'Calvin Klein', id: 2938 },
    { name: 'Cartier', id: 880 },
    { name: 'Casio', id: 1491 },
    { name: 'Céline', id: 2279 },
    { name: 'Chanel', id: 1511 },
    { name: 'Chrome Hearts', id: 2263 },
    { name: 'Daniel Wellington', id: 1146 },
    { name: 'Designer Collection', id: 4432 },
    { name: 'Diesel', id: 3538 },
    { name: 'Dior', id: 1539 },
    { name: 'Dolce & Gabbana', id: 2436 },
    { name: 'Elegant', id: 2612 },
    { name: 'Emporio Armani', id: 1119 },
    { name: 'Fendi', id: 1767 },
    { name: 'Festina', id: 1263 },
    { name: 'Forecast', id: 2907 },
    { name: 'Fosili', id: 1173 },
    { name: 'Franck Muller', id: 1133 },
    { name: 'Fusili', id: 3433 },
    { name: 'Genova', id: 3208 },
    { name: 'Gucci', id: 1098 },
    { name: 'Guess', id: 2908 },
    { name: 'Hublot', id: 1266 },
    { name: 'Idis', id: 3307 },
    { name: 'Invicta', id: 1004 },
    { name: 'Keep Moving', id: 2868 },
    { name: 'Kuber', id: 2516 },
    { name: 'Lamborghini', id: 1220 },
    { name: 'Longines', id: 3315 },
    { name: 'Lookworld', id: 938 },
    { name: 'Louis Vuitton', id: 2132 },
    { name: 'Marble', id: 2574 },
    { name: 'Marble Brand', id: 2440 },
    { name: 'Mata', id: 2536 },
    { name: 'Mata Gold House', id: 4113 },
    { name: 'Maybach', id: 1650 },
    { name: 'Michael Kors', id: 784 },
    { name: 'Miu Miu', id: 3614 },
    { name: 'Montblanc', id: 1032 },
    { name: 'Moscot', id: 1769 },
    { name: 'Movado', id: 2973 },
    { name: 'Nepic', id: 906 },
    { name: 'Off-White', id: 1771 },
    { name: 'Panerai', id: 1036 },
    { name: 'Patek Philippe', id: 705 },
    { name: 'Police', id: 2670 },
    { name: 'Porsche', id: 2819 },
    { name: 'Porsche Design', id: 1975 },
    { name: 'Prada', id: 1735 },
    { name: 'Quamer', id: 2814 },
    { name: 'Rado', id: 1035 },
    { name: 'Ray-Ban', id: 1692 },
    { name: 'Rikon', id: 4047 },
    { name: 'Roberto Cavalli', id: 3601 },
    { name: 'Rolex', id: 731 },
    { name: 'Sagar', id: 3226 },
    { name: 'Salvatore Ferragamo', id: 1789 },
    { name: 'Seiko', id: 3908 },
    { name: 'SKMEI', id: 1510 },
    { name: 'Sonam', id: 2490 },
    { name: 'St. Alexander', id: 2646 },
    { name: 'Sunikko', id: 3211 },
    { name: 'Sushito', id: 4203 },
    { name: 'Swatch', id: 2975 },
    { name: 'TAG Heuer Carrera', id: 3018 },
    { name: 'Tang Tang Yi Biao', id: 2842 },
    { name: 'Tissot', id: 3502 },
    { name: 'Tom Ford', id: 1963 },
    { name: 'Tommy Hilfiger', id: 3151 },
    { name: 'Valentino', id: 2381 },
    { name: 'Versace', id: 695 },
    { name: 'Wlisth', id: 3382 },
    { name: 'Alkaline', id: 4433 },
    { name: 'Anderne', id: 4434 },
    { name: 'Anna Karin', id: 4435 },
    { name: 'Apple Watch', id: 4436 },
    { name: 'Ariel', id: 4437 },
    { name: 'Benz', id: 4438 },
    { name: 'Binbond', id: 4439 },
    { name: 'Boss', id: 4440 },
    { name: 'Carrera', id: 4441 },
    { name: 'Coss', id: 4442 },
    { name: 'Curren', id: 4443 },
    { name: 'Cussi', id: 4444 },
    { name: 'Dalicell', id: 4445 },
    { name: 'Domsem', id: 4446 },
    { name: 'Dudun', id: 4447 },
    { name: 'Duracell', id: 4448 },
    { name: 'Google', id: 4449 },
    { name: 'Hermès', id: 4450 },
    { name: 'Joefox', id: 4451 },
    { name: 'Lee', id: 4452 },
    { name: 'Marc Jacobs', id: 4453 },
    { name: 'Maxell', id: 4454 },
    { name: 'Moonlight', id: 4455 },
    { name: 'Nice', id: 4456 },
    { name: 'Omega', id: 4457 },
    { name: 'Panasonic', id: 4458 },
    { name: 'Poedagar', id: 4459 },
    { name: 'Premium', id: 4460 },
    { name: 'Reward', id: 4461 },
    { name: 'Richard Mille', id: 4462 },
    { name: 'Sony', id: 4463 },
    { name: 'Stand', id: 4464 },
    { name: 'Sunnice', id: 4465 },
    { name: 'Tianqiu', id: 4466 },
    { name: 'Timex', id: 4467 },
    { name: 'Tudor', id: 4468 },
    { name: 'Valentine', id: 4469 },
    { name: 'Valenzo', id: 4470 },
    { name: 'Van Cleef & Arpels', id: 4471 },
    { name: 'Varta', id: 4472 },
    { name: 'Yittong', id: 4473 },
    { name: 'Nike', id: 4476 },
    { name: 'Tory Burch', id: 4477 },
    { name: 'Tommy Jeans', id: 4478 },
    { name: 'Balmain', id: 4479 },
    { name: 'Fred', id: 4480 },
    { name: 'Pandora', id: 4481 },
    { name: 'Swarovski', id: 4482 },
    { name: 'Tiffany & Co.', id: 4483 },
];

export const CATEGORIES: Category[] = [
    // Parent Categories
    { id: 4296, name: 'Glasses Nigeria', parent: 0 },
    { id: 4287, name: 'Watches Nigeria', parent: 0 },

    // Watch Categories
    { id: 4542, name: 'Affordable Watches Nigeria', parent: 4287 },
    { id: 4558, name: 'Automatic Watches Nigeria', parent: 4287 },
    { id: 4556, name: 'Black Watches Nigeria', parent: 4287 },
    { id: 4547, name: 'Budget Watches Nigeria', parent: 4287 },
    { id: 4557, name: 'Chronograph Watches Nigeria', parent: 4287 },
    { id: 4550, name: 'Gold Watches Nigeria', parent: 4287 },
    { id: 4549, name: 'Luxury Watches Under 100000 Naira', parent: 4287 },
    { id: 4288, name: "Men's Watches Nigeria", parent: 4287 },
    { id: 4563, name: 'Military Watches Nigeria', parent: 4287 },
    { id: 4561, name: 'Minimalist Watches Nigeria', parent: 4287 },
    { id: 4562, name: 'Oversized Watches Nigeria', parent: 4287 },
    { id: 4548, name: 'Premium Watches Nigeria', parent: 4287 },
    { id: 4559, name: 'Quartz Watches Nigeria', parent: 4287 },
    { id: 4552, name: 'Rose Gold Watches Nigeria', parent: 4287 },
    { id: 4554, name: 'Rubber Watches Nigeria', parent: 4287 },
    { id: 4551, name: 'Silver Watches Nigeria', parent: 4287 },
    { id: 4553, name: 'Stainless Steel Watches Nigeria', parent: 4287 },
    { id: 4541, name: 'Unisex Watches Nigeria', parent: 4287 },
    { id: 4566, name: 'Watches Abeokuta', parent: 4287 },
    { id: 4565, name: 'Watches Abuja', parent: 4287 },
    { id: 4564, name: 'Watches Lagos', parent: 4287 },
    { id: 4521, name: 'Watches Port Harcourt', parent: 4287 },
    { id: 4560, name: 'Waterproof Watches Nigeria', parent: 4287 },
    { id: 4289, name: "Women's Watches Nigeria", parent: 4287 },
    { id: 4532, name: "Women's Analog Watches Nigeria", parent: 4289 },
    { id: 4539, name: "Women's Business Watches Nigeria", parent: 4289 },
    { id: 4537, name: "Women's Casual Watches Nigeria", parent: 4289 },
    { id: 4603, name: "Women's Chain Watches Nigeria", parent: 4289 },
    { id: 4533, name: "Women's Digital Watches Nigeria", parent: 4289 },
    { id: 4540, name: "Women's Dress Watches Nigeria", parent: 4289 },
    { id: 4538, name: "Women's Fashion Watches Nigeria", parent: 4289 },
    { id: 4535, name: "Women's Leather Watches Nigeria", parent: 4289 },
    { id: 4536, name: "Women's Luxury Watches Nigeria", parent: 4289 },
    { id: 4534, name: "Women's Sport Watches Nigeria", parent: 4289 },
    { id: 4522, name: "Men's Analog Watches Nigeria", parent: 4288 },
    { id: 4529, name: "Men's Business Watches Nigeria", parent: 4288 },
    { id: 4322, name: "Men's Casual Watches Nigeria", parent: 4288 },
    { id: 4555, name: "Men's Chain Watches Nigeria", parent: 4288 },
    { id: 4523, name: "Men's Digital Watches Nigeria", parent: 4288 },
    { id: 4530, name: "Men's Dress Watches Nigeria", parent: 4288 },
    { id: 4528, name: "Men's Fashion Watches Nigeria", parent: 4288 },
    { id: 4525, name: "Men's Leather Watches Nigeria", parent: 4288 },
    { id: 4320, name: "Men's Luxury Watches Nigeria", parent: 4288 },
    { id: 4524, name: "Men's Sport Watches Nigeria", parent: 4288 },
    
    // Glasses Categories
    { id: 4596, name: 'Designer Glasses Nigeria', parent: 4296 },
    { id: 4567, name: 'Eyeglasses Nigeria', parent: 4296 },
    { id: 4597, name: 'Fashion Glasses Nigeria', parent: 4296 },
    { id: 4297, name: "Men's Glasses", parent: 4296 },
    { id: 4572, name: 'Sunglasses Nigeria', parent: 4296 },
    { id: 4298, name: "Women's Glasses", parent: 4296 },
    { id: 4583, name: "Men's Acetate Glasses Nigeria", parent: 4297 },
    { id: 4577, name: "Men's Aviator Glasses Nigeria", parent: 4297 },
    { id: 4337, name: "Men's Casual Glasses", parent: 4297 },
    { id: 4580, name: "Men's Gaming Glasses Nigeria", parent: 4297 },
    { id: 4581, name: "Men's Metal Glasses Nigeria", parent: 4297 },
    { id: 4578, name: "Men's Oval Glasses Nigeria", parent: 4297 },
    { id: 4582, name: "Men's Plastic Glasses Nigeria", parent: 4297 },
    { id: 4576, name: "Men's Rectangle Glasses Nigeria", parent: 4297 },
    { id: 4579, name: "Men's Round Glasses Nigeria", parent: 4297 },
    { id: 4575, name: "Men's Square Glasses Nigeria", parent: 4297 },
    { id: 4584, name: "Men's Titanium Glasses Nigeria", parent: 4297 },
    { id: 4594, name: "Women's Acetate Glasses Nigeria", parent: 4298 },
    { id: 4587, name: "Women's Aviator Glasses Nigeria", parent: 4298 },
    { id: 4590, name: "Women's Cat Eye Glasses Nigeria", parent: 4298 },
    { id: 4591, name: "Women's Gaming Glasses Nigeria", parent: 4298 },
    { id: 4592, name: "Women's Metal Glasses Nigeria", parent: 4298 },
    { id: 4588, name: "Women's Oval Glasses Nigeria", parent: 4298 },
    { id: 4593, name: "Women's Plastic Glasses Nigeria", parent: 4298 },
    { id: 4586, name: "Women's Rectangle Glasses Nigeria", parent: 4298 },
    { id: 4589, name: "Women's Round Glasses Nigeria", parent: 4298 },
    { id: 4585, name: "Women's Square Glasses Nigeria", parent: 4298 },
    { id: 4595, name: "Women's Titanium Glasses Nigeria", parent: 4298 },
    { id: 4544, name: 'Watches Under 20000 Naira', parent: 4542 },
    { id: 4545, name: 'Watches Under 30000 Naira', parent: 4542 },
    { id: 4546, name: 'Watches Under 50000 Naira', parent: 4542 },
    { id: 4570, name: 'Blue Light Glasses Nigeria', parent: 4567 },
    { id: 4571, name: 'Computer Glasses Nigeria', parent: 4567 },
    { id: 4598, name: 'Photochromic Blue Cut glasses Nigeria', parent: 4567 },
    { id: 4568, name: 'Prescription Glasses Nigeria', parent: 4567 },
    { id: 4569, name: 'Reading Glasses Nigeria', parent: 4567 },
    { id: 4600, name: 'Full Rim Glasses Nigeria', parent: 4567 },
    { id: 4601, name: 'Rimless Glasses Nigeria', parent: 4567 },
    { id: 4602, name: 'Semi Rimless Glasses Nigeria', parent: 4567 },
    { id: 4599, name: 'TR90 Glasses Nigeria', parent: 4567 },
];


export const ATTRIBUTES: Attribute[] = [
    // Watch Attributes
    { id: 4353, name: 'Automatic', group: 'Movement', type: 'watch' },
    { id: 4356, name: 'Kinetic', group: 'Movement', type: 'watch' },
    { id: 4354, name: 'Manual', group: 'Movement', type: 'watch' },
    { id: 4352, name: 'Quartz', group: 'Movement', type: 'watch' },
    { id: 4355, name: 'Solar', group: 'Movement', type: 'watch' },
    { id: 4362, name: 'Aluminum', group: 'Case Material', type: 'watch' },
    { id: 4363, name: 'Bronze', group: 'Case Material', type: 'watch' },
    { id: 4361, name: 'Carbon Fiber', group: 'Case Material', type: 'watch' },
    { id: 4360, name: 'Ceramic', group: 'Case Material', type: 'watch' },
    { id: 4359, name: 'Gold Plated', group: 'Case Material', type: 'watch' },
    { id: 4357, name: 'Stainless Steel', group: 'Case Material', type: 'watch' },
    { id: 4358, name: 'Titanium', group: 'Case Material', type: 'watch' },
    { id: 4368, name: 'Ceramic', group: 'Band Material', type: 'watch' },
    { id: 4370, name: 'Chain', group: 'Band Material', type: 'watch' },
    { id: 4364, name: 'Leather', group: 'Band Material', type: 'watch' },
    { id: 4369, name: 'Mesh', group: 'Band Material', type: 'watch' },
    { id: 4367, name: 'Nylon', group: 'Band Material', type: 'watch' },
    { id: 4366, name: 'Rubber/Silicone', group: 'Band Material', type: 'watch' },
    { id: 4365, name: 'Stainless Steel', group: 'Band Material', type: 'watch' },
    { id: 4371, name: 'Chronograph', group: 'Features', type: 'watch' },
    { id: 4373, name: 'Date Display', group: 'Features', type: 'watch' },
    { id: 4375, name: 'Dive Bezel', group: 'Features', type: 'watch' },
    { id: 4374, name: 'GMT', group: 'Features', type: 'watch' },
    { id: 4376, name: 'Luminous', group: 'Features', type: 'watch' },
    { id: 4377, name: 'Scratch Resistant', group: 'Features', type: 'watch' },
    { id: 4372, name: 'Water Resistant', group: 'Features', type: 'watch' },
    { id: 4382, name: 'Cushion', group: 'Case Shape', type: 'watch' },
    { id: 4380, name: 'Rectangular', group: 'Case Shape', type: 'watch' },
    { id: 4378, name: 'Round', group: 'Case Shape', type: 'watch' },
    { id: 4379, name: 'Square', group: 'Case Shape', type: 'watch' },
    { id: 4381, name: 'Tonneau', group: 'Case Shape', type: 'watch' },
    { id: 4383, name: 'Analog', group: 'Display', type: 'watch' },
    { id: 4384, name: 'Digital', group: 'Display', type: 'watch' },
    { id: 4385, name: 'Hybrid', group: 'Display', type: 'watch' },
  
    // Glasses Attributes
    { id: 4386, name: 'Aviator', group: 'Frame Style', type: 'glasses' },
    { id: 4393, name: 'Browline', group: 'Frame Style', type: 'glasses' },
    { id: 4391, name: 'Cat-Eye', group: 'Frame Style', type: 'glasses' },
    { id: 4392, name: 'Oversized', group: 'Frame Style', type: 'glasses' },
    { id: 4390, name: 'Rectangle', group: 'Frame Style', type: 'glasses' },
    { id: 4388, name: 'Round', group: 'Frame Style', type: 'glasses' },
    { id: 4394, name: 'Shield', group: 'Frame Style', type: 'glasses' },
    { id: 4389, name: 'Square', group: 'Frame Style', type: 'glasses' },
    { id: 4387, name: 'Wayfarer', group: 'Frame Style', type: 'glasses' },
    { id: 4397, name: 'Acetate', group: 'Frame Material', type: 'glasses' },
    { id: 4400, name: 'Carbon Fiber', group: 'Frame Material', type: 'glasses' },
    { id: 4395, name: 'Metal', group: 'Frame Material', type: 'glasses' },
    { id: 4396, name: 'Plastic', group: 'Frame Material', type: 'glasses' },
    { id: 4398, name: 'Titanium', group: 'Frame Material', type: 'glasses' },
    { id: 4399, name: 'Wood', group: 'Frame Material', type: 'glasses' },
    { id: 4401, name: 'Full-Rim', group: 'Frame Type', type: 'glasses' },
    { id: 4403, name: 'Rimless', group: 'Frame Type', type: 'glasses' },
    { id: 4402, name: 'Semi-Rimless', group: 'Frame Type', type: 'glasses' },
    { id: 4407, name: 'Anti-Glare', group: 'Lens Features', type: 'glasses' },
    { id: 4404, name: 'Blue Light Blocking', group: 'Lens Features', type: 'glasses' },
    { id: 4406, name: 'Photochromic', group: 'Lens Features', type: 'glasses' },
    { id: 4405, name: 'Polarized', group: 'Lens Features', type: 'glasses' },
    { id: 4409, name: 'Prescription Ready', group: 'Lens Features', type: 'glasses' },
    { id: 4408, name: 'UV Protection', group: 'Lens Features', type: 'glasses' },
    { id: 4410, name: 'Clear', group: 'Lens Type', type: 'glasses' },
    { id: 4413, name: 'Gradient', group: 'Lens Type', type: 'glasses' },
    { id: 4412, name: 'Mirrored', group: 'Lens Type', type: 'glasses' },
    { id: 4411, name: 'Tinted', group: 'Lens Type', type: 'glasses' },
];
